version: '3.8'

services:
  postgres:
    image: 'postgres:13.3'
    container_name: povio-assignment-db
    expose:
      - 5432
    ports:
      - '5432:5432'
    env_file:
      - .env
    networks:
      - povio
networks:
  povio:
    external:
      name: povionet
